name: Metrics
on:
  schedule:
    - cron: '0 0/3 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics 1
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: metrics1.svg
          user: sapphi-red
          base: header, activity, repositories, metadata
          config_timezone: Asia/Tokyo
          config_twemoji: no # connect ETIMEDOUT 151.139.237.124:443 happens due to https://github.com/twitter/twemoji/issues/556
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 2%
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_filter: stars:>100
          plugin_notable_from: organization
          plugin_notable_indepth: yes
          plugin_rss: yes
          plugin_rss_limit: 4
          plugin_rss_source: https://trap.jp/author/sappi_red/rss/
          repositories_skipped: piscon2019,piscon2019-2,go-traq
          use_prebuilt_image: yes

      - name: Metrics 2
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: metrics2.svg
          user: sapphi-red
          base: ""
          config_timezone: Asia/Tokyo
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          repositories_skipped: piscon2019,piscon2019-2,go-traq
          use_prebuilt_image: yes
